//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pinetree.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HomeResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public HomeResources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pinetree.Shared.Resources.HomeResources", typeof(HomeResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Pinetree is currently in beta development. Please note that this is our first video production, so the quality may not be optimal. The presentation materials are in English with subtitles, but the narration is in Japanese. We appreciate your understanding as we continue to improve our content and service. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BetaVersionDescription {
            get {
                return ResourceManager.GetString("BetaVersionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Beta Version Notice: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BetaVersionNotice {
            get {
                return ResourceManager.GetString("BetaVersionNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   As documents grow more detailed, we typically organize them with rules and folders. However, traditional file structures lack physical connections between these documents. Pinetree allows you to express content in a &quot;hierarchical&quot; format and navigate via links, enabling readers to naturally understand the relationships between content. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConceptHierarchicalDescription {
            get {
                return ResourceManager.GetString("ConceptHierarchicalDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pinetree is ideal for resume, travel plans, reading notes, and any document requiring both &quot;conciseness&quot; and &quot;detail.&quot; You can keep each piece of content as simple as possible while adding hierarchical details as needed. Experience this new writing style for yourself. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConceptIdealUseDescription {
            get {
                return ResourceManager.GetString("ConceptIdealUseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pinetree draws inspiration from Amazon&apos;s &quot;One Pager&quot; culture, which focuses on condensing key points into a single page. People prefer concise, readable content, yet there are times when detailed information is necessary. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConceptOnePageDescription {
            get {
                return ResourceManager.GetString("ConceptOnePageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create multiple documents when you register for an account. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CreateMultipleDocuments {
            get {
                return ResourceManager.GetString("CreateMultipleDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   feedback に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Users who provide valuable feedback will receive a permanent free pass! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FreePassForFeedback {
            get {
                return ResourceManager.GetString("FreePassForFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Join our community of organized writers and thinkers today! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string JoinCommunity {
            get {
                return ResourceManager.GetString("JoinCommunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pinetree Overview &amp; Demo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OverviewAndDemo {
            get {
                return ResourceManager.GetString("OverviewAndDemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pricing に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Pricing {
            get {
                return ResourceManager.GetString("Pricing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ready to get started? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ReadyToGetStarted {
            get {
                return ResourceManager.GetString("ReadyToGetStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Register に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please start with Playground and we&apos;d appreciate your feedback afterwards. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StartWithPlayground {
            get {
                return ResourceManager.GetString("StartWithPlayground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pinetree is browser-based hierarchical markdown editor に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This 9-minute video covers Pinetree&apos;s core concepts and includes a live demonstration of key features. We&apos;ve implemented the main functionality we envisioned and are now releasing it as a beta version to gather valuable feedback from users. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string VideoDescription {
            get {
                return ResourceManager.GetString("VideoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   We&apos;re currently in a phase where we want as many users as possible to try our service. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WantManyUsers {
            get {
                return ResourceManager.GetString("WantManyUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   What is a Hierarchical Markdown Editor? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WhatIsHierarchical {
            get {
                return ResourceManager.GetString("WhatIsHierarchical", resourceCulture);
            }
        }
    }
}
