//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pinetree.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PricingResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PricingResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pinetree.Shared.Resources.PricingResources", typeof(PricingResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us via Feedback.
        /// </summary>
        public static string ContactUsViaFeedback {
            get {
                return ResourceManager.GetString("ContactUsViaFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Pricing.
        /// </summary>
        public static string CustomPricing {
            get {
                return ResourceManager.GetString("CustomPricing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom integrations and features.
        /// </summary>
        public static string CustomIntegrations {
            get {
                return ResourceManager.GetString("CustomIntegrations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dedicated account management.
        /// </summary>
        public static string DedicatedAccountManagement {
            get {
                return ResourceManager.GetString("DedicatedAccountManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enterprise Plan.
        /// </summary>
        public static string EnterprisePlanTitle {
            get {
                return ResourceManager.GetString("EnterprisePlanTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For organizations requiring custom solutions, advanced integrations, or specialized support. Currently, we are focusing on perfecting our core features for individual and small team use..
        /// </summary>
        public static string EnterprisePlanDescription {
            get {
                return ResourceManager.GetString("EnterprisePlanDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free Plan.
        /// </summary>
        public static string FreePlanTitle {
            get {
                return ResourceManager.GetString("FreePlanTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experience hierarchical Markdown editing for free. Perfect for getting started with organized content creation, though some limitations apply..
        /// </summary>
        public static string FreePlanDescription {
            get {
                return ResourceManager.GetString("FreePlanDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $0.
        /// </summary>
        public static string FreePlanPrice {
            get {
                return ResourceManager.GetString("FreePlanPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These limits are thoughtfully designed to provide excellent value while encouraging growth to our paid plans for expanded usage..
        /// </summary>
        public static string FreePlanFooter {
            get {
                return ResourceManager.GetString("FreePlanFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Started Free.
        /// </summary>
        public static string GetStartedFree {
            get {
                return ResourceManager.GetString("GetStartedFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limited Time Offer:.
        /// </summary>
        public static string LimitedTimeOffer {
            get {
                return ResourceManager.GetString("LimitedTimeOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum characters per file: {0}.
        /// </summary>
        public static string MaximumCharactersPerFile {
            get {
                return ResourceManager.GetString("MaximumCharactersPerFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum files: {0}.
        /// </summary>
        public static string MaximumFiles {
            get {
                return ResourceManager.GetString("MaximumFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum files per level: {0}.
        /// </summary>
        public static string MaximumFilesPerLevel {
            get {
                return ResourceManager.GetString("MaximumFilesPerLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Image: {0}.
        /// </summary>
        public static string MaximumImage {
            get {
                return ResourceManager.GetString("MaximumImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum levels: {0}.
        /// </summary>
        public static string MaximumLevels {
            get {
                return ResourceManager.GetString("MaximumLevels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get 1 year FREE access to Professional Plan!.
        /// </summary>
        public static string OneYearFree {
            get {
                return ResourceManager.GetString("OneYearFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pricing Plans.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to / month.
        /// </summary>
        public static string PerMonth {
            get {
                return ResourceManager.GetString("PerMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority support and consultation.
        /// </summary>
        public static string PrioritySupport {
            get {
                return ResourceManager.GetString("PrioritySupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professional Plan.
        /// </summary>
        public static string ProfessionalPlanTitle {
            get {
                return ResourceManager.GetString("ProfessionalPlanTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock the full potential of hierarchical Markdown editing. Perfect for power users and professionals who need extensive content organization capabilities..
        /// </summary>
        public static string ProfessionalPlanDescription {
            get {
                return ResourceManager.GetString("ProfessionalPlanDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $1.
        /// </summary>
        public static string ProfessionalPlanPrice {
            get {
                return ResourceManager.GetString("ProfessionalPlanPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe for $1/month.
        /// </summary>
        public static string SubscribeForOneMonth {
            get {
                return ResourceManager.GetString("SubscribeForOneMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tailored solutions for your organization.
        /// </summary>
        public static string TailoredSolutions {
            get {
                return ResourceManager.GetString("TailoredSolutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ∞.
        /// </summary>
        public static string Unlimited {
            get {
                return ResourceManager.GetString("Unlimited", resourceCulture);
            }
        }
    }
}
