name: ci/cd
on:
  push:
    branches:
    - main

env:
  AZURE_WEBAPP_PACKAGE_PATH: Pinetree\published
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 9.0.x
  ASPNETCORE_ENVIRONMENT: Production
  SLOT_NAME: swap

jobs:
  build-and-unit-tests:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}

    - name: Restore dependencies
      run: dotnet restore

    - name: Build the project
      run: dotnet build --configuration ${{ env.CONFIGURATION }} --no-restore

    - name: Run Unit Tests
      run: dotnet test Pinetree.Client.TestProject/Pinetree.Client.TestProject.csproj --no-build

    - name: Publish the project
      run: dotnet publish Pinetree/Pinetree.csproj --configuration ${{ env.CONFIGURATION }} --output "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"

    - name: Publish Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: webapp
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

  migrate:
    runs-on: windows-latest
    needs: build-and-unit-tests
    steps:
    - uses: actions/checkout@v4
    - name: Install EF Core tools
      run: dotnet tool install --global dotnet-ef
    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.Pinetree_SPN }}
    - name: Add IP to Azure SQL firewall
      run: |
        $ip = (Invoke-WebRequest -Uri https://api.ipify.org).Content
        Write-Host "GitHub Actions IP: $ip"
        az sql server firewall-rule create `
          --resource-group "pinetree" `
          --server "pinetree" `
          --name "GithubActions-Temporary" `
          --start-ip-address $ip `
          --end-ip-address $ip
    - name: Run database migrations
      run: |
        cd Pinetree
        dotnet ef database update --configuration ${{ env.CONFIGURATION }} --verbose
      env:
        ConnectionStrings__DefaultConnection: ${{ secrets.PRODUCTION_DB_CONNECTION }}
        TypeScriptCompileBlocked: true
    - name: Remove IP from Azure SQL firewall
      if: always()
      run: |
        az sql server firewall-rule delete `
          --resource-group "pinetree" `
          --server "pinetree" `
          --name "GithubActions-Temporary"

  deploy:
    runs-on: windows-latest
    needs: [build-and-unit-tests, migrate]
    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: webapp
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.Pinetree_SPN }}

    - name: Deploy to Green Slot
      uses: azure/webapps-deploy@v2
      with:
        app-name: pinetree
        slot-name: ${{ env.SLOT_NAME }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

    - name: Configure Azure Web App Settings for Green Slot
      run: |
        az webapp config appsettings set --name pinetree --resource-group pinetree --slot ${{ env.SLOT_NAME }} --settings ASPNETCORE_ENVIRONMENT=Production

    - name: Swap Slots
      run: |
        az webapp deployment slot swap --name pinetree --resource-group pinetree --slot ${{ env.SLOT_NAME }}
