name: PR Validation
on:
  pull_request:

env:
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 9.0.x

jobs:
  build-and-test:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --configuration ${{ env.CONFIGURATION }} --no-restore
    
    - name: Run Unit Tests
      run: dotnet test Pinetree.Client.TestProject/Pinetree.Client.TestProject.csproj --no-build --configuration ${{ env.CONFIGURATION }} --logger "trx;LogFileName=test-results.trx" --logger "console;verbosity=detailed"
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: '**/test-results.trx'
    
    - name: Test Report
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: .NET Tests
        path: '**/test-results.trx'
        reporter: dotnet-trx