name: Simple Test

on:
  issue_comment:
    types: [created]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  simple-test:
    runs-on: ubuntu-latest
    steps:
      - name: Just log
        run: |
          echo "Workflow triggered!"
          echo "Event: ${{ github.event_name }}"
          echo "Comment exists: ${{ github.event.comment != null }}"
